<?php
// $Id: mapitourprices.module,v 1.0 2010/23/11 19:28:54 soncco Exp $

 
/**
* Muestra la ayuda y la información del módulo
* @param path which path of the site we're displaying help
* @param arg array that holds the current path as would be returned from arg() function
* @return help text for the path
*/
function mapitourprices_help($path, $arg) {
  $output = '';  
  switch ($path) {
    case "admin/help#mapitourprices":
	case "admin/mapitravel/mapitourprices":
      $output = '<p>'.  t("Shows prices for Machupicchu Travel's tours based on tokens") .'</p>';
      break;
	case "node/add/story":
	case "node/add/tour":
	case "node/add/tours":
	case "node/add/hotel":
	case "node/add/hotels":
      $output = '<p>'.  t("To show 'vallesagrado' prices, write [mapitravel:vallesagrado] on body.") .'</p>';
      break;
  }
  return $output;
} // function mapitourprices_help

/**
* Permisos
* @return array An array of valid permissions for the mapitourprices module
*/
function mapitourprices_permission() {
  return array('administer mapitourprices' => array(
      'title' => t('Administer tokens for Prices'),
   ));
} // function mapitourprices_perm()

/**
 * Implementation for hook_menu().
 */
function mapitourprices_menu() {

  $items = array();
  
  $items['admin/mapitravel'] = array(
    'title' => 'Machupicchu',
    'description' => 'All modules for Machupicchu Travel',
    'position' => 'right',
    'weight' => 0,
    'access arguments' => array('access administration pages'),
  );

  $items['admin/mapitravel/mapitourprices'] = array(
    'title' => 'Machupicchu Tour Prices',
    'description' => 'Config values for Machupicchu Tour Prices',
    'page callback' => 'drupal_get_form',
    'page arguments' => array('mapitourprices_admin'),
    'access arguments' => array('access administration pages'),
   );
  
  return $items;
} // function mapitourprices_menu()

/**
* Página de Administración de Machupicchu Tour Prices
* @return array El Formulario
*/
function mapitourprices_admin() {
  $form = array();

  $form['mapitourprices_url'] = array(
    '#type' => 'textfield',
    '#title' => t('Path for prices'),
    '#size' => 70,
	'#default_value' => variable_get('mapitourprices_url', 'http://media.perunoticias.net/html/prices/tours/'),
    '#maxlength' => 150,
    '#description' => t("The URL must be content / final. eg. http://foo.com/."),
    '#required' => TRUE,
  );
  
    
  $form['mapitourprices_tokens'] = array(
    '#type' => 'textarea',
    '#title' => t('Tokens'),
	'#default_value' => variable_get('mapitourprices_tokens'),
    '#description' => t("Introduce tokens without [], one per line."),
    '#required' => TRUE,
	'#resizable' => TRUE,
  );
  
  $form['mapitourprices_check'] = array(
    '#type' => 'button',
    '#value' => t('Clear cache'),
	'#weight' => 15,
	'#executes_submit_callback' => TRUE,
	'#submit' => array('mapitourprices_clear_cache'),
  );
  
  $form = system_settings_form($form);
  
  $form['#submit'][] = 'mapitourprices_redo';
   
  return $form;
} // function mapitourprices_admin()

function mapitourprices_redo() {
	//mapitourprices_clear_cache(false);
	mapitourprices_startbatch();
}

function mapitourprices_startbatch() {
  $function = 'mapitourprices_middlebatch';
  $batch = $function();
  batch_set($batch);
}

function mapitourprices_middlebatch() {
  global $language;
	$prefix = $language->language;
	
	$defaultTokens = variable_get('mapitourprices_tokens');
	$defaultTokens = explode("\n", $defaultTokens);
	
  $operations = array();
  
  foreach ($defaultTokens as $token) {
    $operations[] = array('mapitourprices_get_file', array($token, t('(Getting @token.html)', array('@token' => $token))));
  }
  
  $batch = array(
    'operations' => $operations,
    'finished' => 'mapitourprices_finished',
  );
  return $batch;
}

function mapitourprices_get_file($token, $operation_details, &$context) {
  global $language;
	$prefix = $language->language;
  
  $url = variable_get('mapitourprices_url', 'http://media.perunoticias.net/html/prices/tours/');
	$cacheDir = drupal_get_path('module', 'mapitourprices') . "/cache/";
  $token = trim($token);
  
  if(!file_exists($cacheDir . $token . ".html")) {
    $data = file_get_contents($url . $prefix . "/" . $token . ".html");
    $fh = fopen($cacheDir . $token . ".html", 'w');
    fwrite($fh, $data);
    fclose($fh);
    $context['results']['newfiles'][] = "$token.html";
  } else {
    $context['results']['oldfiles'][] = t('@token.html exists', array('@token' => $token));
  }
  $context['message'] = t('Loading token "@token"', array('@token' => $token)) . ' ' . $operation_details;
}

function mapitourprices_finished($success, $results, $operations) {
  if ($success) {
    if (isset($results['oldfiles'])) {
      drupal_set_message(t('@count files already existed and were not updated.', array('@count' => count($results['oldfiles']))));
    }
    if (isset($results['newfiles'])) {
      drupal_set_message(t('@count files has been downloaded.', array('@count' => count($results['newfiles']))));
      drupal_set_message(t('New Files: @files', array('@files' => implode(' ', $results['newfiles']))));
    }
  }
  else {
    $error_operation = reset($operations);
    drupal_set_message(t('An error occurred while processing @operation with arguments : @args', array('@operation' => $error_operation[0], '@args' => print_r($error_operation[0], TRUE))));
  }
}

/**
 * Implementation of hook_token_info().
 */
function mapitourprices_token_info() {
	
  $types = array();
  $mapitravel = array();
  
  $types['mapitravel'] = array(
    'name' => t("Machupicchu Tokens"),
    'description' => t("Tokens for Machupicchu Travel."),
  );
  
  $default_tokens = variable_get('mapitourprices_tokens');
  $default_tokens = explode("\n", $default_tokens);
  
 
  foreach($default_tokens as $k => $token) {
	  $mapitravel[$token] = array(
			'name' => 'Tour ' . $token,
			'description' => t('Payment information for ') . $token
	  );
  }
  
  return array(
    'types' => $types,
    'tokens' => array(
      'mapitravel' => $mapitravel,
    ),
  );
}

/**
 * Implements hook_tokens().
 */
function mapitourprices_tokens($type, $tokens, array $data = array(), array $options = array()) {
  
  $cacheDir = drupal_get_path('module', 'mapitourprices') . "/cache/";
  
  $replacements = array();
  
  if ($type == 'mapitravel') {
    foreach ($tokens as $name => $original) {
		$replacements[$original] = 	file_get_contents($cacheDir . trim($name) . ".html");
    }
  }
  
  return $replacements;
}

function mapitourprices_clear_cache ($message = true) {
	$cacheDir = drupal_get_path('module', 'mapitourprices') . "/cache";
	$error = false;
	
	if(!$dh = @opendir($cacheDir)) {
		$error = true;
		return;
	}
	
    while (false !== ($obj = readdir($dh))) {
        if($obj=='.' || $obj=='..') continue;
        if(!@unlink($cacheDir.'/'.$obj)) $error = true;;
    }
	
    closedir($dh);
	
	if($message) {
	
		if(!$error) {
			drupal_set_message(t('The cache dir has been emptied.'));
		} else {
			drupal_set_message(t('Error on clearing.'), 'error');
		}

	}
}

function file_get_contents_curl($url) {
	$ch = curl_init();
 
	curl_setopt($ch, CURLOPT_HEADER, 0);
	curl_setopt($ch, CURLOPT_RETURNTRANSFER, 1);
	curl_setopt($ch, CURLOPT_URL, $url);
 
	$data = curl_exec($ch);
	curl_close($ch);
 
	return $data;
}
